apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /root/palo/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-volume
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/azureuser/wordpress-data
