kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-claim
  labels:
    name: wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: wp-volume
