apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-wp-claim
  labels:
    name: wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: db-volume
